<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, shallowRef, watch } from 'vue'
import {
  ArrowDown, ArrowUp, ArrowUpRight, Bookmark, Check, ChevronDown, Copy, Minus, PencilLine, Plus,
  RotateCw, Shuffle, SlidersHorizontal, Sparkles, WandSparkles,
} from 'lucide-vue-next'
import {
  generateArtistString,
  type Artist, type BracketStyle, type GeneratorMode, type GeneratorResult,
} from '@/core/generator'
import { editArtistString, type EditAction, type TargetFormat } from '@/core/stringEditor'
import { loadArtistLibrary } from '@/data/artistLibrary'
import { useVault } from '@/composables/useVault'
import { normalizeGeneratorPreferences, usePreferences } from '@/composables/usePreferences'
import { copyText } from '@/utils/clipboard'

const props = defineProps<{ editRequest: { text: string; nonce: number } | null }>()
const vault = useVault()
const preferences = usePreferences()
const options = preferences.generator
const artists = shallowRef<readonly Artist[]>([])
const libraryState = ref<'loading' | 'ready' | 'error'>('loading')
const advancedOpen = ref(false)
const result = shallowRef<GeneratorResult | null>(null)
const historyFeedback = ref<'pending' | 'saved' | 'temporary'>('pending')
const resultElement = ref<HTMLElement | null>(null)
const resultMode = ref<GeneratorMode>('standard')
const editorElement = ref<HTMLElement | null>(null)
const editorInput = ref('')
const editorOutput = ref('')
const editorNames = ref<string[]>([])
const editedMode = ref<GeneratorMode>('pure')
const targetFormat = ref<TargetFormat>('nai')
const editMin = ref(0.5)
const editMax = ref(1.5)
const editBracketStyle = ref<BracketStyle>('paren')
const editBracketLevels = ref(0)
const notice = ref('')
const errorNotice = ref(false)
let messageTimer: ReturnType<typeof setTimeout> | undefined

const modeLabels: Record<GeneratorMode, string> = {
  pure: '纯文本', standard: '标准权重', creative: '创意括号', nai: 'NAI 格式',
}
const modeHints: Record<GeneratorMode, string> = {
  pure: '只保留画师名，以逗号分隔。',
  standard: '为每位画师随机添加 (名称:权重)。',
  creative: '用随机层数的括号包裹画师名。',
  nai: '输出可用于 NovelAI 的 权重::名称 :: 格式。',
}
const libraryStatus = computed(() => {
  if (libraryState.value === 'loading') return '正在读取本地画师库…'
  if (libraryState.value === 'error') return '画师库读取失败'
  return `${new Intl.NumberFormat('zh-CN').format(artists.value.length)} 位画师已就绪`
})
const resultIsFavorite = computed(() => !!result.value && vault.favorites.value.some((item) => item.text === result.value?.text))
const editIsFavorite = computed(() => !!editorOutput.value && vault.favorites.value.some((item) => item.text === editorOutput.value))

function flash(text: string, isError = false) {
  notice.value = text
  errorNotice.value = isError
  if (messageTimer) clearTimeout(messageTimer)
  messageTimer = setTimeout(() => { notice.value = '' }, 4000)
}

async function loadLibrary() {
  libraryState.value = 'loading'
  try { artists.value = await loadArtistLibrary(); libraryState.value = 'ready' }
  catch { libraryState.value = 'error' }
}

function changeCount(amount: number) {
  options.count = Math.max(1, Math.min(options.maxCount, options.count + amount))
}
function normalizeCurrentOptions() { normalizeGeneratorPreferences() }
function scrollToSection(selector: string) {
  document.querySelector(selector)?.scrollIntoView({
    behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth',
    block: 'start',
  })
}

async function generate() {
  if (libraryState.value !== 'ready') return
  normalizeCurrentOptions()
  try {
    const generated = generateArtistString(
      artists.value, options, Math.random, preferences.avoidLastArtists ? result.value?.names : undefined,
    )
    result.value = generated
    resultMode.value = options.mode
    historyFeedback.value = 'pending'
    void vault.recordHistory(generated.text, generated.names, options.mode)
      .then(() => {
        if (result.value === generated) historyFeedback.value = vault.storageStatus.value === 'ready' ? 'saved' : 'temporary'
      })
      .catch(() => {
        if (result.value === generated) historyFeedback.value = 'temporary'
      })
    // Call Clipboard API before yielding the user-activation generated by the button click.
    if (preferences.autoCopy) {
      void copyText(generated.text).then(() => flash('新画师串已自动复制'))
        .catch(() => flash('自动复制被浏览器拒绝，请手动复制结果。', true))
    }
    await nextTick()
    if (preferences.autoScroll && resultElement.value && resultElement.value.getBoundingClientRect().bottom > window.innerHeight) {
      resultElement.value.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' })
    }
  } catch (cause) { flash(cause instanceof Error ? cause.message : '生成失败，请重试。', true) }
}

async function copy(value: string) {
  try { await copyText(value); flash('已复制，可以粘贴使用。') }
  catch { flash('自动复制失败，请手动选中文本复制。', true) }
}

async function openEditor(text: string) {
  editorInput.value = text
  editorOutput.value = ''
  await nextTick()
  scrollToSection('#string-editor')
}

watch(() => props.editRequest?.nonce, () => {
  if (props.editRequest) void openEditor(props.editRequest.text)
})

function process(action: EditAction) {
  try {
    const edited = editArtistString(editorInput.value, {
      action, format: targetFormat.value, min: editMin.value, max: editMax.value,
      bracketStyle: editBracketStyle.value, bracketLevels: editBracketLevels.value,
    })
    editorOutput.value = edited.text
    editorNames.value = edited.names
    editedMode.value = action === 'strip' ? 'pure' : targetFormat.value
    flash(action === 'strip' ? '已去除权重' : action === 'reroll' ? '已重新随机强调强度' :
      targetFormat.value === 'standard' || targetFormat.value === 'nai'
        ? '已转换格式，原有数值保留' : '已转换格式；纯文本/括号不保留精确数值')
  } catch (cause) { flash(cause instanceof Error ? cause.message : '无法处理这段画师串。', true) }
}

async function toggleResultFavorite() {
  if (!result.value) return
  try {
    const added = await vault.toggleFavorite(result.value.text, result.value.names, resultMode.value, 'generated')
    flash(added ? vault.storageStatus.value === 'ready' ? '已加入本地收藏' : '仅本次会话收藏；请导出备份' : '已从收藏中移除')
  } catch (cause) { flash(cause instanceof Error ? cause.message : '收藏失败', true) }
}

async function toggleEditedFavorite() {
  if (!editorOutput.value) return
  try {
    const added = await vault.toggleFavorite(editorOutput.value, editorNames.value, editedMode.value, 'edited')
    flash(added ? vault.storageStatus.value === 'ready' ? '编辑结果已收藏' : '仅本次会话收藏；请导出备份' : '已取消收藏')
  } catch (cause) { flash(cause instanceof Error ? cause.message : '收藏失败', true) }
}

async function saveEditedHistory() {
  if (!editorOutput.value) return
  await vault.recordHistory(editorOutput.value, editorNames.value, editedMode.value, 'edited')
  flash(vault.storageStatus.value === 'ready' ? '编辑结果已保存到历史记录' : '编辑结果仅本次会话暂存；请导出备份')
}

onMounted(() => { void loadLibrary() })
onUnmounted(() => { if (messageTimer) clearTimeout(messageTimer) })
</script>

<template>
  <div class="workspace-page">
    <div class="eyebrow"><span class="eyebrow-line"></span> ARTIST STRING GENERATOR</div>
    <h1>生成你的下一组灵感<span class="title-period">.</span></h1>
    <p class="intro">本地随机挑选画师，按你喜欢的格式生成画师串，还能继续编辑与收藏。</p>

    <section class="composer" aria-labelledby="composer-title">
      <div class="composer-heading">
        <div><p class="section-eyebrow">01 / 创建画师串</p><h2 id="composer-title">怎么生成？</h2></div>
        <div class="composer-heading-actions"><button type="button" class="editor-jump" @click="scrollToSection('#string-editor')">直接编辑 <ArrowDown :size="15" aria-hidden="true" /></button><div class="heading-symbol" aria-hidden="true"><Shuffle :size="21" :stroke-width="1.8" /></div></div>
      </div>
      <div class="primary-controls">
        <div class="field count-field" data-tour="count">
          <span id="count-label" class="field-label">画师数量</span>
          <div class="count-mode-switch" role="group" aria-label="画师数量选择模式">
            <button type="button" :aria-pressed="options.countMode === 'fixed'" @click="options.countMode = 'fixed'">指定数量</button>
            <button type="button" :aria-pressed="options.countMode === 'range'" @click="options.countMode = 'range'">随机区间</button>
          </div>
          <div v-if="options.countMode === 'fixed'" class="stepper" role="group" aria-labelledby="count-label">
            <button type="button" :disabled="options.count <= 1" aria-label="减少画师数量" @click="changeCount(-1)"><Minus :size="17" aria-hidden="true" /></button>
            <input v-model.number="options.count" type="number" min="1" :max="options.maxCount" step="1" aria-label="指定画师数量" @change="normalizeCurrentOptions" />
            <button type="button" :disabled="options.count >= options.maxCount" aria-label="增加画师数量" @click="changeCount(1)"><Plus :size="17" aria-hidden="true" /></button>
          </div>
          <div v-else class="count-range" role="group" aria-labelledby="count-label">
            <label>最少 <input v-model.number="options.rangeMin" type="number" min="1" :max="options.maxCount" step="1" aria-label="区间最少画师" @change="normalizeCurrentOptions" /></label>
            <span aria-hidden="true">—</span>
            <label>最多 <input v-model.number="options.rangeMax" type="number" min="1" :max="options.maxCount" step="1" aria-label="区间最多画师" @change="normalizeCurrentOptions" /></label>
          </div>
          <span class="field-help">每次不重复抽取；安全上限 {{ options.maxCount }} 位，可在设置中下调。</span>
        </div>
        <div class="field" data-tour="format">
          <label for="mode" class="field-label">输出格式</label>
          <div class="select-wrap">
            <select id="mode" v-model="options.mode">
              <option value="standard">标准权重</option><option value="pure">纯文本</option>
              <option value="creative">创意括号</option><option value="nai">NAI 格式</option>
            </select>
            <ChevronDown :size="17" aria-hidden="true" />
          </div>
        </div>
      </div>
      <p class="mode-hint">{{ modeHints[options.mode] }}</p>
      <div class="advanced-block">
        <button type="button" class="advanced-trigger" :aria-expanded="advancedOpen" aria-controls="advanced-options" @click="advancedOpen = !advancedOpen">
          <SlidersHorizontal :size="17" aria-hidden="true" /> 更多选项
          <ChevronDown :size="16" class="advanced-chevron" :class="{ 'is-open': advancedOpen }" aria-hidden="true" />
        </button>
        <div v-if="advancedOpen" id="advanced-options" class="advanced-options">
          <div class="advanced-field">
            <label for="min-posts">最低作品数</label>
            <div class="select-wrap compact-select"><select id="min-posts" v-model.number="options.minPosts">
              <option :value="0">不限</option><option :value="100">至少 100</option>
              <option :value="500">至少 500</option><option :value="1000">至少 1,000</option>
            </select><ChevronDown :size="16" aria-hidden="true" /></div>
            <span class="field-help">使用画师库内的作品数量快照</span>
          </div>
          <div v-if="options.mode === 'standard' || options.mode === 'nai'" class="advanced-field">
            <span id="weight-label">随机权重范围</span>
            <div class="weight-range" role="group" aria-labelledby="weight-label">
              <input v-model.number="options.weightMin" aria-label="生成最小权重" type="number" min="0" max="2" step="0.1" @change="normalizeCurrentOptions" />
              <span aria-hidden="true">—</span>
              <input v-model.number="options.weightMax" aria-label="生成最大权重" type="number" min="0" max="2" step="0.1" @change="normalizeCurrentOptions" />
            </div>
            <span class="field-help">可设置 0.0 至 2.0</span>
          </div>
          <template v-if="options.mode === 'creative'">
            <div class="advanced-field"><label for="bracket-style">括号类型</label><div class="select-wrap compact-select"><select id="bracket-style" v-model="options.bracketStyle">
              <option value="paren">圆括号 ( )</option><option value="curly">花括号 { }</option><option value="square">方括号 [ ]</option>
            </select><ChevronDown :size="16" aria-hidden="true" /></div></div>
            <div class="advanced-field"><label for="bracket-levels">括号层数</label><div class="select-wrap compact-select"><select id="bracket-levels" v-model.number="options.bracketLevels">
              <option :value="0">随机 1–5 层</option><option v-for="level in 5" :key="level" :value="level">{{ level }} 层</option>
            </select><ChevronDown :size="16" aria-hidden="true" /></div></div>
          </template>
          <label class="prefix-option"><input v-model="options.withPrefix" type="checkbox" />为每位画师添加 <code>artist:</code> 前缀</label>
        </div>
      </div>
      <div class="composer-footer">
        <span class="library-status" :class="{ 'status-error': libraryState === 'error' }" role="status"><span class="status-dot" aria-hidden="true"></span>{{ libraryStatus }}</span>
        <button class="generate-button" type="button" :disabled="libraryState !== 'ready'" @click="generate">随机生成 <ArrowUpRight :size="18" aria-hidden="true" /></button>
      </div>
      <div v-if="libraryState === 'error'" class="load-error" role="alert">本地画师库无法读取。<button type="button" @click="loadLibrary">重试加载</button></div>
    </section>

    <Transition name="result">
      <section v-if="result" ref="resultElement" class="result-section" aria-labelledby="result-title">
        <div class="result-heading"><span class="result-avatar" aria-hidden="true"><Sparkles :size="20" /></span><div><p class="section-eyebrow">02 / 生成结果</p><h2 id="result-title">你的画师串</h2></div></div>
        <div class="result-panel">
          <div class="result-toolbar"><span>{{ modeLabels[resultMode] }} · {{ result.names.length }} 位画师</span><button type="button" class="copy-button" @click="copy(result.text)"><Copy :size="16" aria-hidden="true" /> 复制结果</button></div>
          <p class="result-text">{{ result.text }}</p>
        </div>
        <div class="result-bottom">
          <p role="status">{{ historyFeedback === 'saved' ? '已保存到本地历史 · 不重复抽取' : historyFeedback === 'temporary' ? '仅本次会话暂存 · 建议导出备份' : '正在保存到本地历史…' }}</p>
          <div class="result-action-group">
            <button type="button" class="regenerate-button" @click="openEditor(result.text)"><PencilLine :size="16" aria-hidden="true" /> 编辑这一串</button>
            <button type="button" class="regenerate-button" :aria-pressed="resultIsFavorite" @click="toggleResultFavorite"><Bookmark :size="16" aria-hidden="true" /> {{ resultIsFavorite ? '已收藏' : '收藏' }}</button>
            <button type="button" class="regenerate-button" @click="generate"><RotateCw :size="16" aria-hidden="true" /> 换一组</button>
          </div>
        </div>
      </section>
    </Transition>

    <section ref="editorElement" id="string-editor" class="editor-section" aria-labelledby="editor-title">
      <div class="result-heading" data-tour="editor"><span class="result-avatar" aria-hidden="true"><WandSparkles :size="20" /></span><div><p class="section-eyebrow">工具 / 二次编辑</p><h2 id="editor-title">把画师串改成你想要的样子</h2></div></div>
      <p class="editor-description">粘贴画师串，或从生成结果、历史记录一键带入。处理只改权重与格式，不重新抽画师；原文不会被覆盖。</p>
      <div class="editor-card panel">
        <label for="editor-input" class="field-label">原始画师串</label>
        <textarea id="editor-input" v-model="editorInput" rows="4" spellcheck="false" placeholder="例如：(artist_a:1.2), (artist_b:0.8)" @input="editorOutput = ''"></textarea>
        <div class="editor-settings">
          <div class="edit-field"><label for="target-format">目标格式 · 四种输出</label><div class="select-wrap compact-select"><select id="target-format" v-model="targetFormat">
            <option value="pure">纯文本 名称</option><option value="standard">标准 (名称:1.0)</option>
            <option value="creative">创意括号 ((名称))</option><option value="nai">NAI 1.0::名称 ::</option>
          </select><ChevronDown :size="16" aria-hidden="true" /></div></div>
          <div v-if="targetFormat === 'standard' || targetFormat === 'nai'" class="edit-field"><span>重随数值权重范围</span><div class="weight-range"><input v-model.number="editMin" aria-label="编辑最小权重" type="number" min="0" max="2" step="0.1" /><span>—</span><input v-model.number="editMax" aria-label="编辑最大权重" type="number" min="0" max="2" step="0.1" /></div></div>
          <template v-if="targetFormat === 'creative'">
            <div class="edit-field"><label for="edit-bracket-style">括号类型</label><div class="select-wrap compact-select"><select id="edit-bracket-style" v-model="editBracketStyle"><option value="paren">圆括号 ( )</option><option value="curly">花括号 { }</option><option value="square">方括号 [ ]</option></select><ChevronDown :size="16" aria-hidden="true" /></div></div>
            <div class="edit-field"><label for="edit-bracket-levels">括号层数</label><div class="select-wrap compact-select"><select id="edit-bracket-levels" v-model.number="editBracketLevels"><option :value="0">随机 1–5 层（转换时保留原括号层数）</option><option v-for="level in 5" :key="level" :value="level">{{ level }} 层</option></select><ChevronDown :size="16" aria-hidden="true" /></div></div>
          </template>
        </div>
        <div class="editor-actions">
          <button type="button" @click="process('strip')">去除权重</button>
          <button type="button" :disabled="targetFormat === 'pure'" :title="targetFormat === 'pure' ? '纯文本没有权重' : undefined" @click="process('reroll')">{{ targetFormat === 'creative' ? '重随括号层数' : '重随权重' }}</button>
          <button type="button" class="editor-primary-action" @click="process('convert')">转换为{{ modeLabels[targetFormat] }}</button>
        </div>
        <p class="field-help">标准 ↔ NAI 会保留精确权重；纯文本与创意括号无法表达原数值。未加权的画师转数值格式时使用 1.0，原始输入不会被覆盖。</p>
        <div v-if="editorOutput" class="editor-output">
          <div class="editor-output-head"><span>处理结果 · {{ editorNames.length }} 项</span><button type="button" @click="copy(editorOutput)"><Copy :size="15" aria-hidden="true" /> 复制</button></div>
          <p class="result-text">{{ editorOutput }}</p>
          <div class="editor-output-actions">
            <button type="button" @click="editorInput = editorOutput; editorOutput = ''"><RotateCw :size="15" aria-hidden="true" /> 用结果继续编辑</button>
            <button type="button" @click="saveEditedHistory"><Check :size="15" aria-hidden="true" /> 保存到历史</button>
            <button type="button" :aria-pressed="editIsFavorite" @click="toggleEditedFavorite"><Bookmark :size="15" aria-hidden="true" /> {{ editIsFavorite ? '已收藏' : '收藏结果' }}</button>
          </div>
        </div>
      </div>
      <button type="button" class="back-to-generator" @click="scrollToSection('.composer')"><ArrowUp :size="15" aria-hidden="true" /> 回到生成设置</button>
    </section>
    <p v-if="notice" class="toast-inline" :class="{ 'message-error': errorNotice }" role="status">{{ notice }}</p>
    <p class="page-note">生成与编辑都在浏览器中完成；图片功能仅在画师库的图片视图中按需访问 Danbooru。</p>
  </div>
</template>
